title: Bridgeconstructor
description: Programme d'intelligence artificiel pour choisir le type, les matériaux et le prix pour la construction de ponts
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
